import { useEffect, useState } from 'preact/hooks';
import { getJson, type Session } from './api.js';
import { formatDateTime } from './format.js';
import { StatusIcon } from './tile.js';
import type { Config, TlsView } from './types.js';

const DAY_MS = 86_400_000;

type Https = Extract<TlsView, { mode: 'https' }>;
type Http = Extract<TlsView, { mode: 'http' }>;

const VALIDITY_TEXT: Record<Https['validity'], string> = {
  valid: 'Valid',
  'expiring-soon': 'Expiring soon',
  expired: 'Expired',
  'not-yet-valid': 'Not yet valid'
};

const CLASS_TEXT: Record<Https['class'], string> = {
  valid: 'Complete and trusted',
  'degraded-incomplete-chain': 'Chain incomplete: an intermediate certificate is missing',
  'degraded-san': 'Missing a configured name',
  'degraded-untrusted': 'Not trusted by the configured certificate authority'
};

function HttpBody({ tls, signIn }: { tls: Http | undefined; signIn: boolean }) {
  return (
    <>
      <p class="alert-severity">
        <StatusIcon level={signIn ? 'critical' : 'warning'} />
        HTTPS is off: pages{signIn ? ', the password and the session cookie' : ''} cross the network
        unencrypted.
      </p>
      {tls?.reason === 'env' && (
        <p>
          Turned off by <code>PIPULSE_TLS=off</code>.
        </p>
      )}
      {tls?.reason === 'state' && tls.stateMode === 'legacy-http' && (
        <p>
          HTTPS is ready: run <code>sudo pipulse tls enable</code> on the Pi.
        </p>
      )}
    </>
  );
}

function HttpsBody({ tls, now }: { tls: Https; now: number }) {
  const bad = tls.validity === 'expired' || tls.validity === 'not-yet-valid';
  const soon = tls.validity === 'expiring-soon';
  const daysLeft = Math.floor((tls.notAfter - now) / DAY_MS);
  return (
    <>
      <p>
        {tls.source === 'operator' ? 'Your certificate (PIPULSE_TLS_CERT)' : 'Generated by PiPulse'}
      </p>
      <p class={bad || soon ? 'alert-severity' : undefined}>
        {(bad || soon) && <StatusIcon level={bad ? 'critical' : 'warning'} />}
        {VALIDITY_TEXT[tls.validity]}: valid until {formatDateTime(tls.notAfter)}
        {!bad && ` (${daysLeft} days left)`}
      </p>
      <p class={tls.class === 'valid' ? undefined : 'alert-severity'}>
        {tls.class !== 'valid' && <StatusIcon level="warning" />}
        {CLASS_TEXT[tls.class]}
        {tls.missingNames.length > 0 && `: ${tls.missingNames.join(', ')}`}
      </p>
      <p>Names: {[...tls.sans.dns, ...tls.sans.ip].join(', ')}</p>
      <p>
        SHA-256: <code class="fingerprint">{tls.fingerprint}</code>
      </p>
      {tls.reload.state === 'failing' && (
        <p class="alert-severity">
          <StatusIcon level="warning" />A replacement certificate was not loaded
          {tls.reload.lastError ? `: ${tls.reload.lastError}` : ''}. The current one is still in
          use.
        </p>
      )}
    </>
  );
}

/** How the dashboard is served: the certificate in use, or a warning that it's plain HTTP. */
export function CertificateSection({ session }: { session: Session }) {
  const [config, setConfig] = useState<Config | 'loading' | 'error'>('loading');
  useEffect(() => {
    getJson<Config>('/api/config').then(setConfig, () => setConfig('error'));
  }, []);
  return (
    <section aria-labelledby="settings-certificate">
      <h2 id="settings-certificate">Certificate</h2>
      {config === 'loading' && <p class="waiting">Loading</p>}
      {config === 'error' && (
        <p class="waiting">Couldn't load the HTTPS status from the PiPulse server.</p>
      )}
      {typeof config === 'object' &&
        (config.tls?.mode === 'https' ? (
          <HttpsBody tls={config.tls} now={config.serverTime ?? Date.now()} />
        ) : (
          <HttpBody tls={config.tls} signIn={session.editable} />
        ))}
    </section>
  );
}
